language: python
python:
- '3.5'
dist: trusty
install:
- pip install s3cmd
- pip install delegator.py
script:
- python devtools/create_key_file.py
- python devtools/push-docs-to-s3.py
- rm keys.crt
after_success:
- echo "Website Updated"
env:
  global:
  - secure: k4xLGR5R/QSyugjPB93KLdjQwpNA3tslDd8ZoFGX62AbjPc51B8VddSCP26qPwJ3DoQ0PaYC7L5uKPzPzlK0p5jm0QD3EZK5rzg7vHnwFByLzIbTWRGNO63VWid2d+O02H3Pop8aEdjjkW4hD3/JSjBT8WIVog8FeL1YVJqgyDd54i2zBwWR++/PdQ05qD2d/5LmajaZzEHJK/liCcDaAeUJZHslv3zHVtGO098j7VQgFfSTAhxpFEaYEuUP/xjr5OxV0mTBhEGEo+b6rzWiUlS7WdfDb2426GY/fc0ZtFM7QBnNPxsGI+pteMNHTvJL/DWpBFTdgN/IK6MAzZnsu2uvOJ59oV4ZDl9cTfzTyCZ+56SHaveUkVq2Vwnly98bUFwBbZufOwbUCamfDshcBIZrdiKnU+SFcrjjgOXMTULhYnSXvExJYQew1pzW9rDoj+GTTFZ5BDoQ2EOIYmFAAJOtsiiZcBuvOHe7J2Jp9f/URVyAkei8ADTB52vK4UEQ8XdwBO1X6ha2RYXwVCcySUesFktqTFjDzcJ53WNBkdUzCRwLSt/rNDy9yzmNQITiU5bX/kaSPBvjrss10XTNub83oXSp0XvDnqdVh21p9hIG3ahVw2gcg/gCpgM102CsU2P2dCX4kYThsC1ZADZecXJf2CmiEJ4H27RQ5/UegAg=
  - secure: dlT7d5aIkFyJxu7mL+YJEBysOPea8IHG0mDHBFsVFWvRuLHwM/dhBlOQArFrNe26k8KlR9CIw1ZUM05wWGH40kluHj//jCwwZTkO+7/l2OpLeQB1Lb2ZYl84TXdE9DXN4YvMnNzD35ISp9yaH675vFO4jKIlK5Is4fqoSxdLAYQWkEDbq/TFBBnFYcxNbtUdmuUUhc+K4eoJiZi/ayrQUJOXGCAUsXwCdLs3OMAqn/VXmb/5iDkUMc/mb7/VMTB7xgBVY4XRJ/FP6RcY5a2KNBfim8U/ssIJsgKSGsbSlsDKofPjmaC+AWuFy3OQ5B0F6x7tlBmic7tHdHOeJ7d7wLvvk8fnFA1/ma/yF2Yz1rAVqU44lWoGYajTTR5xYioYv37n/u/aagL8/8lRU5K/75xYx0uAYYKMJmXC6vj1sO1oH9hT2m0hx8CpjSwuMDPm/MzkUEoIsuApOCteWdKLTyvMYh6QaDbeRl9Pg+CFWU2eyNiMDlumDEIsWoi4cwtFdZl1gy3GZy8ibWjJv32Bkxn9VAgNN4G+OSp2MCxt768DJFX5zeB6/IZCb4GzNYBq/8t/nO4qw+UI7+3xWtdhqeQgUeM+XgrkloEVmlwyIqcdO7FHG6gkbrbzW0GfEKPGn8UXKwKubOS7a6lULWfqmzph2Kr0tNEgMFyTU9XS6dU=
