name: Automatic Website Push
on: [push]
jobs:
  Website_Update:
    runs-on: ubuntu-latest

    steps:
      - run: pip install s3cmd==2.0.2
      - run: pip install delegator.py==0.1.1
      - run: python devtools/create_key_file.py
      - run: python devtools/push-docs-to-s3.py
      - run: rm keys.crt
      - run: echo "Website Updated"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
