name: Automatic Website Push
on: [push]
jobs:
  Website_Update:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
    steps:
      - run: pip install s3cmd==2.0.2
      - run: pip install delegator.py==0.1.1
      - run: ls ../deepchem.io
      - run: python ../deepchem.io/devtools/create_key_file.py
      - run: python ../deepchem.io/devtools/push-docs-to-s3.py
      - run: rm ../deepchem.io/keys.crt
      - run: echo "Website Updated"
